### ISSUE TITLE
Ordinal number strings lost ending point

### ISSUE THREAD

**Issue by hbugdoll** [luyadev/yii-helpers#18]
Ordinal numbers in German-speaking countries are built with cardinal numbers followed by a point:
- 1st = 1.
- 2nd = 2.
- …
- 24th = 24.
- …

If the input string is such an ordinal number, `StringHelper::typeCastNumeric()` strips the ending point (e.g. `"5."` is casted to `"5"`) 
https://github.com/luyadev/yii-helpers/blob/006f1e7473497c7fbbd5319faff1e6c2bc01f856/src/helpers/StringHelper.php#L156
because `StringHelper::isFloat()` detects the ordinal number before as float (`"5." == "5"` returns `true`) in
https://github.com/luyadev/yii-helpers/blob/006f1e7473497c7fbbd5319faff1e6c2bc01f856/src/helpers/StringHelper.php#L176
however PHP’s `is_float()` does not.

The special case can be handled by catching ordinal numbers with RegEx `/\d+\./`
I would provide a PR.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | current 
| PHP Version      | 8.x

Edit: Corrected to L156 instead of L159.

**Comment by nadar** [comment]
afaik the idea behind `::typeCastNumeric` is to have an int value instead of string, for example `(string) 1` will be casted to `(int) 1` this is mainly a problem when working databases and/or json values.

so you say:

```php
StringHelper::typeCastNumeric("2.") // results in (int) 2 instead of "2." string?
```

**Comment by hbugdoll** [comment]
Exactly! `StringHelper::isFloat()` returns wrongly `true` for a string with an ordinal number within and so `StringHelper::typeCastNumeric()` is casting to int.
